### ISSUE TITLE
Adding Steps to FirebaseDB

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/Senior_Networking#3]
## Acceptance Criteria

- [ ] Steps are added successfully to the database
- [ ] The database is sectioned into days / months / years

### Tasks
- [ ] Add the DB
- [ ] Add the Tables / Documents to the DB
- [ ] Give it some data
